services:
  db:
    container_name: postgres-filemanager
    image: postgres:14.1
    environment:
      POSTGRES_USER: filemanager
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filemanager
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  filemanager-api:
    container_name: filemanager-api
    image: filemanager/filemanager-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/filemanager
      SPRING_DATASOURCE_USERNAME: filemanager
      SPRING_DATASOURCE_PASSWORD: password
      AWS_S3_MOCK: "true"
      EMAIL_ENABLED: "false"
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  filemanager-react:
    container_name: filemanager-react
    image: filemanager/filemanager-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - filemanager-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
